### ISSUE TITLE
Cross mod compatability error causing client crash.

### ISSUE THREAD

**Issue by Chaogomu** [AK9Official/All-of-Fabric#10]
Mods involved; 
  Arcane Magic
  Cleanview
  Fabric Toys

When you trigger an Arcane Magic cutscene (place a relic in an analyzer) the player client will immediately crash if Cleanview is installed.

If Cleanview is not installed then the cutscene can begin but the client will crash near the end if Fabric Toys is installed.

Once triggered an Arcane Magic cutscene must be fully completed or else it will begin again on world load (effects both single and multiplayer)

Removing both Cleanview and Fabric Toys allows the cutscene to finish.

**Comment by ImAK9** [comment]
Fixed in 3.1.1

**Comment by Blayyke** [comment]
Any logs?

**Comment by calloatti** [comment]
Closed. No longer relevant. We are on 1.14.4-4.1.0 now.
