### ISSUE TITLE
All of Fabric 3.2.0a  multiple things I have noticed.

### ISSUE THREAD

**Issue by MrPurple6411** [AK9Official/All-of-Fabric#17]
A lot of ores are being disabled after gen causing holes in the fabric of reality.....  also the ones that do gen still as superores will just drop nothing when you break them such as nickel
![2019-06-29_20 38 00](https://user-images.githubusercontent.com/7858500/60523062-4efa2a80-9ca7-11e9-9506-5331810d2b60.png)

noticed nickel is enabled in super ores config.   also several other ores that are not used in any recipes as well.

also battle towers seem to be not very rare and have a tendancy to spawn next to each other..
![2019-06-30_10 21 01](https://user-images.githubusercontent.com/7858500/60523185-89fc5e00-9ca7-11e9-999d-c0b1b586c8d4.png)
![2019-06-30_11 18 21](https://user-images.githubusercontent.com/7858500/60523187-89fc5e00-9ca7-11e9-950c-e68216272bb7.png)

**Comment by calloatti** [comment]
Closed because no longer relevant, we are on MC 1.14.4 now
