### ISSUE TITLE
3.2.0a glowing mushrooms don't have texture and are invisible

### ISSUE THREAD

**Issue by OuweMickey** [AK9Official/All-of-Fabric#18]
As title said, glowing mushrooms in the nether appear invisible and are impossible to walk trough (like ghost blocks)

When placing torch (or something), they appear and show the purple 'no texture' texture. Then it's possible to remove and the proper mushroom appear in inventory.

**Comment by OuweMickey** [comment]
Strangely, after two new logins, the problem disappeared.

**Comment by ImAK9** [comment]
Glad it fixed itself, be sure to report if it keps happening. Feel free to reopen issue if so.
