### ISSUE TITLE
Crash report: Game crashes when rightclicking villager

### ISSUE THREAD

**Issue by moonheart08** [AK9Official/All-of-Fabric#2]
The game crashes with java.lang.StackOverflowError whenever you right-click a villager. This should be reproducable every time, so i will not be posting a crash log (You'll be able to obtain one by right-clicking a villager)

**Comment by ImAK9** [comment]
@moonheart08 Will have this fixed in next patch.

**Comment by ImAK9** [comment]
@moonheart08 Fixed in: https://github.com/AK9Official/All-of-Fabric/releases/tag/1.3.0
