### ISSUE TITLE
buff backpacks AOF-1.14.4-4.0.1

### ISSUE THREAD

**Issue by calloatti** [AK9Official/All-of-Fabric#23]
change default size to 18, 36, 54?

**Comment by Shnupbups** [comment]
Do you really want one item able to carry a double chest's storage? That seems excessive. The backpacks are already laughably easy to get in comparison with vanilla's portable storage solutions (Shulker Boxes or Ender Chests and Silk Touch Pickaxes) and increasing their storage to such extremes would only make this worse.

**Comment by ImAK9** [comment]
buffed all backpacks by 1 row in 4.0.2
