### ISSUE TITLE
Version 2.3.0 crashing

### ISSUE THREAD

**Issue by DeathsGun** [AK9Official/All-of-Fabric#3]
When updating to 2.3.0 the client crashes instantly disabling BetterUtilities does not work:
[crash-2019-05-25_14.42.44-client.txt](https://github.com/AK9Official/All-of-Fabric/files/3219386/crash-2019-05-25_14.42.44-client.txt)

**Comment by ImAK9** [comment]
@DeathsGun Are you using any different version of Java other than 8?

**Comment by DeathsGun** [comment]
Ok i launched with java 12 and it works now but i now join the server it misses some sound files of waddles

**Comment by ImAK9** [comment]
Yeah, Waddles i bork atm... 2.3.1 will fix that

**Comment by ImAK9** [comment]
Fixed in v2.3.1 check #releases
