### ISSUE TITLE
amethystmod-1.1.1.jar renders sword in hand incorrectly

### ISSUE THREAD

**Issue by calloatti** [AK9Official/All-of-Fabric#37]
https://www.curseforge.com/minecraft/mc-mods/amethyst-mod-fabric

![2019-08-05_23 22 05](https://user-images.githubusercontent.com/12817862/62568585-ed0f8080-b863-11e9-80ed-bed6d90d4ee8.png)

**Comment by Jack406** [comment]
esto fue Solucionado en la nueva version de Amethyst

**Comment by coderbot16** [comment]
("This was fixed in the new version of Amethyst")
