### ISSUE TITLE
Chunk claim count is too low for larger bases

### ISSUE THREAD

**Issue by orbwoi** [AK9Official/All-of-Fabric#4]
1. Chunk claim count is too low for larger bases. Right now you can only claim 10 chunks. I recommend you upgrade this to at least 16 chunks so that larger bases can be claimed by players.

2. IT is annoying that you cannot excavate stone, sand, gravel, or dirt. Please revert this change.

3. Small coal from immersive underground are 9:1 with normal coal. This means they each cannot quite smelt one item. Consider changing them to 8:1 so that each coal can smelt one item. Also consider a recipe to convert them into normal coal.

**Comment by ImAK9** [comment]
@orbwoi Everything fixed/added in 3.0.0
