### ISSUE TITLE
[Suggestion] Move from RAR to tar.gz

### ISSUE THREAD

**Issue by spannerman79** [AK9Official/All-of-Fabric#40]
Would it be possible to change to using `tar.gz` instead of `rar` for the server file?

It would make it easier to `wget` onto my linux server, and to extract it all I would have to do is `tar -xvzf file.tar.gz`

Also for some people with a control panel based system that only allows `zip` based compression the `zip` lib on those WebUI panels can handle `tar.gz`

**Comment by ImAK9** [comment]
I could totally do that!

**Comment by riskable** [comment]
I agree this would be a helpful change.  You could even use `.tar.xz` (e.g. `tar -Jxvf` and `tar -Jxcf`--the capital J indicates xz format which is more efficient than gzip, bzip2, and .rar's LZSS-based algo).

**Comment by spannerman79** [comment]
`.tar.xz` is for one time storage - which I use when I need to back something up to my NAS. So not exactly ideal.  Personally wouldn't affect me but if anyone uses a Web based UI/hosting panel it will time out as `.tar.xz` will use more CPU to decompress compared to `.tar.gz`

**Comment by Lartza** [comment]
What about Windows users though? I personally think zip is best of both worlds since it's extractable from Windows explorer unlike other formats. And even where supported on Windows tar.gz can be a two step extract. I'm saying this as a fully Linux server admin.

**Comment by coderbot16** [comment]
Imo Zip is "good enough" for pretty much all cases and is the most compatible. RAR requires proprietary software to even access the data in most cases.

**Comment by spannerman79** [comment]
> What about Windows users though?

Ugh... windows users... well, there are those but how many even know how to setup a server correctly?  Just looking at r/admincraft its clear most don't - or they use a GSP (game service provider)

**Comment by Lartza** [comment]
I see plenty on the various discords I'm on. It's not rocket science to extract and run the bat file, even port forward. There's even the rare kind that has a Windows Server home server and runs MC on that.

**Comment by ImAK9** [comment]
files are now .zip

**Comment by spannerman79** [comment]
Good enough for me, Closing.
