### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by alivebacon** [AK9Official/All-of-Fabric#41]
I was trying to load this for the first time and the loading screen stuck on 1/3 models for bakery.
I don't wanna UL my logs but I know that Minecraft should load fine on this machine. My machine doesn't even lag that much while it loads.

**Comment by ImAK9** [comment]
Hey, check your RAM in MultiMC.

**Comment by alivebacon** [comment]
The logs mention a stone rod failing to load.

**Comment by alivebacon** [comment]
> Hey, check your RAM in MultiMC.

How?

**Comment by alivebacon** [comment]
Can you look for mods that have a stone rod in AOF?

**Comment by Gbergz** [comment]
you change RAM here: [https://gyazo.com/5f0ddb9816fe3c4fc33054c858e929ef](https://gyazo.com/5f0ddb9816fe3c4fc33054c858e929ef)

**Comment by alivebacon** [comment]
> you change RAM here: https://gyazo.com/5f0ddb9816fe3c4fc33054c858e929ef

I thought he meant a ram dump.
What shud the min and max be? I have them at default.

**Comment by Gbergz** [comment]
> > you change RAM here: https://gyazo.com/5f0ddb9816fe3c4fc33054c858e929ef
> 
> I thought he meant a ram dump.
> What shud the min and max be? I have them at default.

I think 5-6 should be fine, could go higher if you want. Probably not necessary though.

**Comment by alivebacon** [comment]
> > > you change RAM here: https://gyazo.com/5f0ddb9816fe3c4fc33054c858e929ef
> > 
> > 
> > I thought he meant a ram dump.
> > What shud the min and max be? I have them at default.
> 
> I think 5-6 should be fine, could go higher if you want. Probably not necessary though.

I assume you mean 5-6 gigs.
I have 8 gigs of RAM, of which 6.93GB can be used. 5-6 gigs seems scarily huge.

**Comment by Gbergz** [comment]
yes gigs, 4 should also be fine. I played AOF normal with that.

**Comment by Gbergz** [comment]
@AK9Official knows this better. ;)

**Comment by alivebacon** [comment]
Hmm. 1-2 gigs crashed.

**Comment by Gbergz** [comment]
Yeah that's too low.

**Comment by alivebacon** [comment]
What about permgen?

**Comment by Gbergz** [comment]
I don't know about that one, leave it for now.

**Comment by alivebacon** [comment]
Now trying 2-3 gigs. Probably gonna crash.

**Comment by alivebacon** [comment]
It did.
It only got stuck on the loading screen with 512MB-1024MB.

**Comment by alivebacon** [comment]
It's broken. I can't boot it anymore. We need a new update. I think the mods are breaking it.

**Comment by Gbergz** [comment]
Works totally fine for me! Try 4 gigs.

**Comment by alivebacon** [comment]
Min or max?

**Comment by Gbergz** [comment]
4168 on both

**Comment by alivebacon** [comment]
ok

**Comment by alivebacon** [comment]
It's booted into the loading screen now.

**Comment by alivebacon** [comment]
thanks, it seems to work now

**Comment by Gbergz** [comment]
😄 👍

**Comment by ImAK9** [comment]
AOF: Normal requires ATLEAST 4GB. Blame 1.14 for that one...

**Comment by ghost** [comment]
Permagen is not used in java 8.
