### ISSUE TITLE
Support for Optifine/OptiFabric?

### ISSUE THREAD

**Issue by Claw256** [AK9Official/All-of-Fabric#42]
Using OptiFabric and Optifine with this mod pack causes it to crash immediately upon launching the pack via MultiMC. Here is the crash log generated by MultiMC: [latest.log](https://github.com/AllOfFabric/AOF-Normal/files/3618468/latest.log)

**Comment by ImAK9** [comment]
Optifine is not supported in AOF: Normal and therefore closing this issue.
