### ISSUE TITLE
Suggestion: Delete the \mods\mamiyaotaru folder

### ISSUE THREAD

**Issue by calloatti** [AK9Official/All-of-Fabric#5]
That folder contains volxelmap data for saved worlds, so probably should not be included in the pack.

**Comment by ImAK9** [comment]
Tbh, I have no idea why the author chose to make the local voxelmap data generate in the /mods folder... I’ll export without it next update! Thanks for the heads up.

**Comment by ImAK9** [comment]
Wont be included in 3.0.0
