### ISSUE TITLE
Game crashes when I saw Elytra

### ISSUE THREAD

**Issue by OuweMickey** [AK9Official/All-of-Fabric#6]
When me and my son (Open to Lan) both arrived to an Elytra, both to separate EndCity's. The game crashed.
Now we can't enter the world anymore without crashing

[Crash Report](https://www.dropbox.com/s/isnlbtrqo61c4cp/crash-2019-05-31_14.53.56-client.txt?dl=0)

**Comment by ImAK9** [comment]
A fix would be to remove The One Probe and add Hwyla instead till 2.4.0 is out.

**Comment by OuweMickey** [comment]
Wow, You're quick!

Tnx.... That did the job :)

**Comment by ImAK9** [comment]
Glad it helped!

**Comment by ImAK9** [comment]
Fixed in 3.0.0
