### ISSUE TITLE
Spice of Fabric has no tooltips.

### ISSUE THREAD

**Issue by Chaogomu** [AK9Official/All-of-Fabric#7]
Spice of Fabric lowers food values to 0 without any indication. Eating a single food item repeatedly will still show the same tooltip as when you first ate it.

My main suggestion for fixing this is to just remove Spice of Fabric. There's already no client-side indication that it's there so might as well remove it from the pack so people don't report a "food not working" bug.

**Comment by ImAK9** [comment]
Feel free to report this to the proper Issue Tracker at: https://github.com/Siphalor/spiceoffabric/issues

**Comment by Siphalor** [comment]
Never reported it to me but it's because AppleSkin was always outdated when I published new releases of Spice of Fabric (still not fixed).

**Comment by calloatti** [comment]
spice of fabric has been removed for now since 1.14.4-4.0.0
