### ISSUE TITLE
Swapping wand breaks after only one use (v2.3.1)

### ISSUE THREAD

**Issue by OuweMickey** [AK9Official/All-of-Fabric#8]
The Swapping Wand breaks after only one use. Every time again...
(in creative it breaks too, but gives a new one)

**Comment by ImAK9** [comment]
There is not much I can do about this other than reporting it to the proper Issue Tracker for the mod... As I've described in the README file of AoF.

Feel free to Report it here: https://github.com/romelo333/notenoughwands1.8.8/issues and I'll add it as soon as it's fixed.

**Comment by calloatti** [comment]
Fixed in AOF-1.14.4-4.0.0: Not Enough Wands (notenoughwands-1.14-1.7.5.beta.jar) removed

Not Enough Wands is broken for now.
