### ISSUE TITLE
Earthworks is not in 3.0.0

### ISSUE THREAD

**Issue by cauliflower69** [AK9Official/All-of-Fabric#9]
Just a heads up. It was added in the change log but not on the client or server. Looks really interesting

**Comment by ImAK9** [comment]
@cauliflower69 Wow, I goofed that one... Thanks for the heads up!

**Comment by cauliflower69** [comment]
No problems. Done the same myself on more than one occasion.

**Comment by ImAK9** [comment]
@cauliflower69 It's actually in, it's just called Groundworks instead.
